page_url_id = '?sortby=4&pageno='

page_404_title = 'Page Not Found'

product_class_id = 'js-product-url'

product_title_id = 'c-product-box__title'

urls = ["https://www.digikala.com/search/category-mobile-accessories/",
        'https://www.digikala.com/search/category-mobile-phone/',
        'https://www.digikala.com/search/category-wearable-gadget/',
        'https://www.digikala.com/search/category-headphone-headset-microphone/',
        'https://www.digikala.com/search/category-speaker/',
        'https://www.digikala.com/search/category-camera/',
        'https://www.digikala.com/search/category-camera-accessories/',
        'https://www.digikala.com/search/category-binoculars/',
        'https://www.digikala.com/search/category-telescope/',
        'https://www.digikala.com/search/category-game-console/',
        'https://www.digikala.com/search/category-computer-parts/',
        'https://www.digikala.com/search/category-notebook-netbook-ultrabook/',
        'https://www.digikala.com/search/category-laptop-accessories/',
        'https://www.digikala.com/search/category-tablet/',
        'https://www.digikala.com/search/category-car-charger/',
        'https://www.digikala.com/search/category-tablet-accessories/',
        'https://www.digikala.com/search/category-battery-charger-and-accesories/',
        'https://www.digikala.com/search/category-network-cam/',
        'https://www.digikala.com/search/category-network/',
        'https://www.digikala.com/search/category-office-machines/',
        
        'https://www.digikala.com/search/category-cars/',
        'https://www.digikala.com/search/category-motorbike/',
        'https://www.digikala.com/search/category-power-tools/',
        'https://www.digikala.com/search/category-consumable-parts/',
        'https://www.digikala.com/search/category-non-electrical-tools/',
        'https://www.digikala.com/search/category-construction-tools-and-equipment/',
        'https://www.digikala.com/search/category-gardening-tools/',
        'https://www.digikala.com/search/category-lighting/',
        'https://www.digikala.com/search/category-safety-tools/',
        'https://www.digikala.com/search/category-protection-and-security-equipment/',
        
        'https://www.digikala.com/search/category-mens-apparel/',
        'https://www.digikala.com/search/category-men-clothing/',
        'https://www.digikala.com/search/category-men-shoes/',
        'https://www.digikala.com/search/category-men-accessories/',
        'https://www.digikala.com/search/category-womens-apparel/',
        'https://www.digikala.com/search/category-women-clothing/',
        'https://www.digikala.com/search/category-women-shoes/',
        'https://www.digikala.com/search/category-women-accessories/',
        'https://www.digikala.com/search/category-women-jewelry/',
        'https://www.digikala.com/search/category-women-gold-jewelry/',
        'https://www.digikala.com/search/category-men-sportswear/',
        'https://www.digikala.com/search/category-women-sportwear/',
        'https://www.digikala.com/search/category-men-sport-shoes-/',
        'https://www.digikala.com/search/category-women-sport-shoes-/',
        
        'https://www.digikala.com/search/category-health-and-bathroom-tools/',
        'https://www.digikala.com/search/category-kids-apparel/',
        'https://www.digikala.com/search/category-toys/',
        'https://www.digikala.com/search/category-entertainment-and-games-equipment/',
        'https://www.digikala.com/search/category-safety-and-care/',
        'https://www.digikala.com/search/category-baby-bedding/',
        'https://www.digikala.com/search/category-promenade-and-travel-accessories/',
        
        'https://www.digikala.com/search/category-groceries/',
        'https://www.digikala.com/search/category-dairy/',
        'https://www.digikala.com/search/category-protein-foods/',
        'https://www.digikala.com/search/category-breakfast/',
        'https://www.digikala.com/search/category-beverages/',
        'https://www.digikala.com/search/category-fruits-and-vegetables/',
        'https://www.digikala.com/search/category-ready-made-canned-food/',
        'https://www.digikala.com/search/category-frozen-food/',
        'https://www.digikala.com/search/category-snacks/',
        'https://www.digikala.com/search/category-canned-food/'
        'https://www.digikala.com/search/category-dried-fruit-nuts/',
        
        'https://www.digikala.com/search/category-beauty/',
        'https://www.digikala.com/search/category-personal-care/',
        'https://www.digikala.com/search/category-electrical-personal-care/',
        'https://www.digikala.com/search/category-gift-set/',
        'https://www.digikala.com/search/category-perfume-all/',
        'https://www.digikala.com/search/category-health-care/',
        
        'https://www.digikala.com/search/category-video-audio-entertainment/',
        'https://www.digikala.com/search/category-decorative/',
        'https://www.digikala.com/search/category-carpet/',
        'https://www.digikala.com/search/category-home-appliance/',
        'https://www.digikala.com/search/category-pet/',
        'https://www.digikala.com/search/category-serving/',
        'https://www.digikala.com/search/category-lighting/',
        'https://www.digikala.com/search/category-home-kitchen-appliances/',
        'https://www.digikala.com/search/category-detergents/',
        'https://www.digikala.com/search/category-tissue-paper/',
        'https://www.digikala.com/search/category-sleeping/',
        'https://www.digikala.com/search/category-bath/',
        'https://www.digikala.com/search/category-bedroom/',
        'https://www.digikala.com/search/category-watercloset/',
        'https://www.digikala.com/search/category-pesonal-appliance-accessories/',
        'https://www.digikala.com/search/category-gardening-tools/',
        
        'https://www.digikala.com/search/book-and-media/publication/',
        'https://www.digikala.com/search/category-audio-book/',
        'https://www.digikala.com/search/category-multimedia-training-pack/',
        'https://www.digikala.com/search/category-software/',
        'https://www.digikala.com/search/category-film-video-content/',
        'https://www.digikala.com/search/category-stationery/',
        'https://www.digikala.com/search/category-musicalinstruments/',
        'https://www.digikala.com/search/category-carpet/',
        'https://www.digikala.com/search/category-handicraft/',
        
        'https://www.digikala.com/search/category-traveling-equipment/',
        'https://www.digikala.com/search/category-bicycle/',
        'https://www.digikala.com/search/category-hiking-and-camping/',
        'https://www.digikala.com/search/category-travel-accessories/',
        'https://www.digikala.com/search/category-umbrella-1/',
        'https://www.digikala.com/search/category-sport/',
        'https://www.digikala.com/search/category-aerobic/',
        
       ]